image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules/
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  - npm install
  - ./node_modules/.bin/webpack --progress -p
  - cp index.html ./public
  - cp app.js  ./public
  artifacts:
    paths:
    - public
  only:
    - master